# GitHub Actions Workflow for Vercel Deployment
name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Export web build
        run: npx expo export --output-dir web-build

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --confirm
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}