# GitHub Actions Workflow for Vercel Deployment
name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Set up environment for Tailwind CSS
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Build Tailwind CSS
        run: npm run build

      - name: Export web build
        run: npx expo export --output-dir web-build

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
